name: Run Data pipeline

on:
  push:
    branches:
      -  main


jobs:
  run-data-pipeline:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_TOKEN_KEY: ${{ secrets.AWS_TOKEN_KEY }}
      INFLUXDB_TOKEN: ${{ secrets.INFLUXDB_TOKEN }}
      INFLUXDB_ORG: ${{ secrets.INFLUXDB_ORG }}
      INFLUXDB_BUCKET: ${{ secrets.INFLUXDB_BUCKET }}
      INFLUXDB_ADMIN_USER: ${{ secrets.INFLUXDB_ADMIN_USER }}
      INFLUXDB_ADMIN_PASSWORD: ${{ secrets.INFLUXDB_ADMIN_PASSWORD }}
      INFLUXDB_USER: ${{ secrets.INFLUXDB_USER }}
      INFLUXDB_USER_PASSWORD: ${{ secrets.INFLUXDB_USER_PASSWORD }}

    steps:
    #clone le repo dans la VM Ubuntu
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose -f docker-compose.ci.yml up --build -d

      #installer et configuration de python pour faciliter les installations
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: Install requirements
        run: pip install -r test/requirements.txt
      
      - name: Run pytest
        run: pytest -v



      
      
